default[:hydra_jetty][:git_repo]   = 'git://github.com/projecthydra/hydra-jetty.git'
default[:hydra_jetty][:git_ref]    = 'master'
default[:hydra_jetty][:user]       = 'hydra_jetty'
default[:hydra_jetty][:group]      = 'hydra_jetty'
default[:hydra_jetty][:dir]        = '/etc/hydra_jetty'
default[:hydra_jetty][:java_opts]  = '-XX:+CMSPermGenSweepingEnabled -XX:+CMSClassUnloadingEnabled -XX:PermSize=64M -XX:MaxPermSize=128M'
default[:hydra_jetty][:start_file] = 'start.jar'
